database = [#Rome
			{ 'restaurantname' : 'Pizzeria Napoli', 'city' : 'Rome', 'cuisine' : 'Italian', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Pasta House', 'city' : 'Rome', 'cuisine' : 'Italian', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Il Cavallino', 'city' : 'Rome', 'cuisine' : 'Italian', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'Leonidas', 'city' : 'Rome', 'cuisine' : 'Mediterranean', 'pricing' : 'Average' },
			{ 'restaurantname' : 'The Mussel Shed', 'city' : 'Rome', 'cuisine' : 'Mediterranean', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Sushi Roma', 'city' : 'Rome', 'cuisine' : 'Japanese', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'Ching Chang', 'city' : 'Rome', 'cuisine' : 'Chinese', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Chong', 'city' : 'Rome', 'cuisine' : 'Chinese', 'pricing' : 'Expensive' },
			#London
			{ 'restaurantname' : 'Bingo Burgers', 'city' : 'London', 'cuisine' : 'American', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Sallys Seafood', 'city' : 'London', 'cuisine' : 'Mediterranean', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Da Gonzo', 'city' : 'London', 'cuisine' : 'Italian', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'The Wasabi House', 'city' : 'London', 'cuisine' : 'Japanese', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Buffalo Boys', 'city' : 'London', 'cuisine' : 'American', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Steaks and Fries', 'city' : 'London', 'cuisine' : 'American', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'The Golden Dragon', 'city' : 'London', 'cuisine' : 'Chinese', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'Everything Fried', 'city' : 'London', 'cuisine' : 'Chinese', 'pricing' : 'Cheap' },
			#Berlin
			{ 'restaurantname' : 'Don Camillo', 'city' : 'Berlin', 'cuisine' : 'Italian', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'La Cantina', 'city' : 'Berlin', 'cuisine' : 'Italian', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Happy Sushi', 'city' : 'Berlin', 'cuisine' : 'Japanese', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Burger Factory', 'city' : 'Berlin', 'cuisine' : 'American', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Texas Steak House', 'city' : 'Berlin', 'cuisine' : 'American', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'El Pescador', 'city' : 'Berlin', 'cuisine' : 'Mediterranean', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Akropolis Grill', 'city' : 'Berlin', 'cuisine' : 'Mediterranean', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Soul Food', 'city' : 'Berlin', 'cuisine' : 'Chinese', 'pricing' : 'Average' },
			{ 'restaurantname' : 'The Talking Duck', 'city' : 'Berlin', 'cuisine' : 'Chinese', 'pricing' : 'Expensive' },
			#Tokyo
			{ 'restaurantname' : 'Pizza Place', 'city' : 'Tokyo', 'cuisine' : 'Italian', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Roshis Ramen', 'city' : 'Tokyo', 'cuisine' : 'Japanese', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Shinjuku Sushi', 'city' : 'Tokyo', 'cuisine' : 'Japanese', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Ichiban', 'city' : 'Tokyo', 'cuisine' : 'Japanese', 'pricing' : 'Expensive' },
			{ 'restaurantname' : 'Tapas Bar', 'city' : 'Tokyo', 'cuisine' : 'Mediterranean', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Bobs Diner', 'city' : 'Tokyo', 'cuisine' : 'American', 'pricing' : 'Average' },
			{ 'restaurantname' : 'Hasia Ung', 'city' : 'Tokyo', 'cuisine' : 'Chinese', 'pricing' : 'Cheap' },
			{ 'restaurantname' : 'Wang Jo', 'city' : 'Tokyo', 'cuisine' : 'Chinese', 'pricing' : 'Average' },
			{ 'restaurantname' : 'The Jasmin Dragon', 'city' : 'Tokyo', 'cuisine' : 'Chinese', 'pricing' : 'Expensive' }]
